matrix:
  include:
    - os: linux
      dist: bionic
    - os: linux
      dist: xenial
    - os: linux
      dist: trusty

language: node_js

node_js:
  - '12'
  - '10'

addons:
  apt:
    packages:
      - xvfb

cache: yarn

install:
  - yarn
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

script:
  - yarn test
  - yarn report-coverage